############################################################
# This config file defines a k8s Deployment for the        #
# bigchaindb/mongodb-monitoring-agent:latest Docker image  #
#                                                          #
# It connects to a MongoDB instance in a separate pod,     #
# all remote MongoDB instances in the cluster,             #
# and also to MongoDB Cloud Manager (an external service). #
# Notes:                                                   #
# MongoDB agents connect to Cloud Manager on port 443.     #
############################################################

apiVersion: v1
kind: Service
metadata:
  name: mon-agent-svc
  namespace: default
  labels:
    name: mon-agent-svc
spec:
  selector:
    app: mon-agent-app
  ports:
  - port: 8080
    targetPort: 8080
    name: mon-agent-port
  type: LoadBalancer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bdb
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mon-agent-app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mdb-mon-agent
        image: bigchaindb/mongodb-monitoring-agent:latest
        args:
        - start
        env:
        - name: MMS_API_KEY
          value: $TODO, Get from ConfigMap or kubectl command-line argument
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          hostPort: 8080
          name: mon-agent-port
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 768Mi
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 10
      restartPolicy: Always
