############################################################
# This config file defines a k8s Deployment for the        #
# bigchaindb/mongodb-monitoring-agent:latest Docker image  #
#                                                          #
# It connects to a MongoDB instance in a separate pod,     #
# all remote MongoDB instances in the cluster,             #
# and also to MongoDB Cloud Manager (an external service). #
# Notes:                                                   #
# MongoDB agents connect to Cloud Manager on port 443.     #
############################################################

apiVersion: v1
kind: Service
metadata:
  name: mdb-mon-svc
  namespace: default
  labels:
    name: mdb-mon-svc
spec:
  selector:
    app: mdb-mon-dep
  type: ClusterIP
  clusterIP: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mdb-mon-dep
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mdb-mon-dep
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mdb-mon
        image: bigchaindb/mongodb-monitoring-agent:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: MMS_API_KEY
          valueFrom:
            configMapKeyRef:
             name: mdb-mon
             key: api-key
        - name: MONGO_HOST:
          value: mdb-svc
        resources:
          limits:
            cpu: 200m
            memory: 768Mi
      restartPolicy: Always
